nexpy/nxrefine

- src/nxrefine/nxrefine.py
- src/nxrefine/plugins/refine/find_maximum.py
- src/nxrefine/plugins/refine/find_peaks.py
- src/nxrefine/scripts/nxcombine.py
- src/nxrefine/scripts/nxfind.py
- src/nxrefine/scripts/nxmax.py
* Removes twotheta and gonpitch from the Dmat and Dvec. These two angles are not coupled in our configuration because the detector is not on a two-theta arm.
* Removes the previous record of nxcombine when a CCTW merge is repeated.
* Uses the NXfield chunks property, rather than reading chunk sizes from the file.
> Test transformations

- src/nxrefine/nxrefine.py
- src/nxrefine/nxserver.py
* Fixes an issue with synchronizing file queues between processes.
* Uses the Python Queue `maxsize` parameter to limit worker jobs.
* Fixes an issue with qsub job names.
* Fixes a problem with copying transmissions between entries.
> Fix-worker-queue

- src/nxrefine/nxreduce.py
- src/nxrefine/nxserver.py
* Fix dictionary reference to server settings.
* Allow run command (e.g., 'qsub' and 'pdsh') switches to be added to the settings.
> Fix-server-settings

- src/nxrefine/nxdatabase.py
- src/nxrefine/nxserver.py
* Fixes the file path used in the NXDatabase `sync_file` function.
* Ensures that all NXFileQueue permissions are updated after each queue operation.
> Fix-database-paths

- src/nxrefine/nxreduce.py
* Fixes punches when the hole radius is larger than the Brillouin Zone along one axis.
> Fix punches when they overlap Brillouin Zones.

- src/nxrefine/nxbeamline.py
If a directory name has the wrong pattern, it will not be included in the wrapper file entries.
> Fix raw file directory lists at CHESS

- src/nxrefine/plugins/refine/calibrate_powder.py
- src/nxrefine/plugins/refine/find_maximum.py
* Replaces call to `np.float` and `np.int` with recommended `float` and `int`, respectively.
> Remove call to deprecated NumPy float function

- src/nxrefine/plugins/refine/refine_lattice.py
The attribute is stored in the NXReduce instance
> Fixes the reference to hkl_tolerance

- src/nxrefine/nxbeamline.py
- src/nxrefine/nxdatabase.py
- src/nxrefine/nxreduce.py
- src/nxrefine/nxrefine.py
* Makes the NXReduce root object read-only by default.
* Defines a context manager for NXReduce instances that is used to unlock and lock the root objects for writing.
* Allows the number of entries to be updated in the database.
> Make-root-readonly

- src/nxrefine/nxreduce.py
- src/nxrefine/nxsettings.py
- src/nxrefine/plugins/refine/edit_settings.py
* Only stores server information in the default settings.
* Only stores experiment location in the experiment settings.
* Ensures both are initialized correctly.
* Fixes an issue when a NXRefine plugin accesses a file with read/write privilege. This prevents the NXRefine context manager from locking the file after completing I/O, unless it was already read-only.
> Improve settings consistency

- src/nxrefine/nxreduce.py
- src/nxrefine/nxrefine.py
* Fixes a bug caused by clashing file locks when a NXReduce instance requests its associated NXRefine instance to write parameters.
* All write locks are handled separately in each class by separate context managers.
> Improve I/O within NXReduce and NXRefine instances

- src/nxrefine/nxdatabase.py
- src/nxrefine/nxreduce.py
* Fixes an issue with determining whether tasks are complete when the original database is no longer available. The existence of NXProcess groups created when a task is complete is now used to verify completion.
* Fixes an incompatibility with SQLAlchemy v2.0 which requires SQL commands to be wrapped by a `text` function.
> Fix issues with loss of database history

- .github/workflows/sphinx.yml
* Specify both `main` and `docs` as valid branches within which to run the Github Action to publish documentation.
> Allow both `main` and `docs` branches for action

- src/nxrefine/plugins/experiment/edit_settings.py
* Allows the dialog to launch when the current settings are inconsistent with the selected directory.
> Allow 'Edit Settings' to work with faulty defaults

- .github/workflows/sphinx.yml
* Github pushes to the docs branch will now trigger Sphinx rendering.
* Manual updates are still allowed.
> Allow documentation updates on push

- README.md
- src/nxrefine/nxreduce.py
- src/nxrefine/nxrefine.py
* Forces the root to reload when locking the file for writing in both the NXReduce and NXRefine classes. This currently fails if the file has been modified since first being opened.
> Add reloads to contextual menus

- src/nxrefine/nxreduce.py
- src/nxrefine/nxsymmetry.py
- src/nxrefine/nxutils.py
* Adds a subclass to ProcessPoolExecutor to automatically set the context to spawn subprocesses. This should reduce the allocated memory.
* Improves use of contextual menus to reduce lockfile exceptions in multiple processes.
* Improves the calculation of polar_max with multiple entries.
> Fix-concurrent-memory

- src/nxrefine/nxrefine.py
- src/nxrefine/nxsettings.py
* If there is no detector orientation stored in the
NeXus file, NXRefine will use the previous default.
> Use old orientation in initializing NXRefine

- src/nxrefine/nxreduce.py
* If a monitor has not been properly defined on an instrument, the `read_monitor` function returns an array of ones. In defined, the sample transmission is corrected for the monitor. If not, the sample transmission will implicitly include a monitor correction.
> Return a monitor weight of 1 if no monitor is defined.

- src/nxrefine/nxbeamline.py
- src/nxrefine/nxreduce.py
* Ensures that a meaningful error message is output when the instrument name has not been set in settings.
> Improve-beamline-error

- src/nxrefine/nxutils.py
- src/nxrefine/plugins/experiment/calibrate_powder.py
- src/nxrefine/plugins/experiment/create_mask.py
- src/nxrefine/plugins/refine/find_maximum.py
* Defines a new utility function for determining if the y-axis of detector images should be flipped.
* Uses the new function in the "Calibrate Powder", "Create Mask", and "Find Maximum" dialogs.
> Use-detector-orientation

- src/nxrefine/nxrefine.py
- src/nxrefine/plugins/refine/refine_lattice.py
* Fixes a bug when defining peak masks before the polar angles have been read.
* Tweaks the size of the peak list window.
> Fix-polar-max-setting

- src/nxrefine/nxlogger.py
- src/nxrefine/nxserver.py
- src/nxrefine/plugins/server/manage_workflows.py
* If `server_type` is set to None, calls to `add_task` are executed directly in a worker thread.
* This removes the need for the file-based queue in systems where it is buggy.
* The `asyncio` library is used instead of `subprocess` to allow immediate execution, with `async` functions to record the output.
> Add-async-option

- src/nxrefine/nxserver.py
- src/nxrefine/plugins/server/manage_server.py
- src/nxrefine/plugins/server/manage_workflows.py
- src/nxrefine/scripts/nxserver.py
* Reverts to using the `subprocess` module, instead of `asyncio`, since there is no time-saving.
* Ensures that worker threads created for running tasks directly are terminated properly.
* Ensures that the server type can be set to None with the `nxserver` script.
* Update Manage Workflows and Manage Servers dialog
> Fix-direct-tasks

- src/nxrefine/nxbeamline.py
- src/nxrefine/nxreduce.py
- src/nxrefine/nxserver.py
- src/nxrefine/plugins/refine/refine_lattice.py
* Creates a new NXReduce log function to wrap calls to logger.info in a NXLock context manager.
* Creates a new NXReduce server_settings dictionary to read directly from the settings rather than launching a new NXServer.
> Use file locking on log files to prevent simultaneous writes

- src/nxrefine/nxreduce.py
- src/nxrefine/nxutils.py
* Allows the 'concurrency' setting to be used to select the ProcessPoolExecutor method.
* This is a choice between 'spawn', the default, and 'fork'.
> Allows different concurrency methods to be used

- src/nxrefine/nxutils.py
- src/nxrefine/plugins/server/manage_server.py
* Shuts down the resource tracker process when a ProcessPoolExecutor is shut down.
* Ensures 'pdsh' is only invoked to monitor processes when it is used in the run command.
> Shutdown-tracker

- src/nxrefine/nxutils.py
* Adds a check for the multiprocessing method before shutting the resource tracker down.
> Check that multiprocessing is not using the 'fork' method

- src/nxrefine/nxbeamline.py
- src/nxrefine/nxreduce.py
* Fixes a bug where `time_path` was not initialized before checking for its existence.
> Fix NXBeamLine code

- LICENSE
- pyproject.toml
* Adds a text version of the license, since setuptools does not support PDF files.
> Add a text version of the license to be installed by setuptools.

- README.md
- pyproject.toml
- src/nxrefine/nxrefine.py
- src/nxrefine/plugins/refine/define_lattice.py
This replaces the dependency on [CCTBX](https://cctbx.github.io/) with [GEMMI](https://gemmi.readthedocs.io/en/latest/). This makes nxrefine installable using pip, uv, etc.
The only user-noticable changes should be:
- The string representation of a space group stored in `NXRefine.space_group` no longer has a space between the space group symbol and the setting number (when there are multiple settings). E.g., `F d -3 m :2` has changed to `F d -3 m:2`. This should have no backwards-compatibility implications, since both CCTBX and GEMMI can parse both string formats.
- The list of Miller indices generated by `NXRefine.miller` and used by `NXRefine.two_thetas`, `NXRefine.indices`, etc. are in a slightly different order. They are still sorted by decreasing d-spacing, but indices with the same …
> Replace CCTBX dependency with GEMMI dependency
