nexpy/nxrefine

src/nxrefine/nxsettings.py, src/nxrefine/nxutils.py, src/nxrefine/plugins/refine/new_configuration.py, src/nxrefine/plugins/refine/new_scan.py, src/nxrefine/plugins/refine/new_settings.py, src/nxrefine/scripts/nxsettings.py
* Adds an instrument section to 'settings.ini'
* Allows `gonpitch` to be set as a scan variable
* Uses `importlib` for Julia imports
=> Generalize settings

src/nxrefine/plugins/refine/calibrate_powder.py, src/nxrefine/plugins/refine/create_mask.py, src/nxrefine/plugins/refine/new_configuration.py, src/nxrefine/plugins/refine/new_settings.py
* Fixes input of instrument settings in the SettingsDialog
* Fixes source location in the ConfigurationDialog
* Allows copying of powder calibrations and masks to other entries
=> Fix-dialogs

src/nxrefine/plugins/refine/calibrate_powder.py
* Improves calibration imports.
* Uses the PyFAI Fit2D geometry for the detector distance.
* Uses a single AzimuthalIntegrator for refinements and cake plots.
=> Improve-calibration-dialog

setup.cfg, src/nxrefine/nxbeamline.py, src/nxrefine/nxdatabase.py, src/nxrefine/nxreduce.py, src/nxrefine/nxutils.py, src/nxrefine/plugins/refine/__init__.py, src/nxrefine/plugins/refine/import_scans.py, src/nxrefine/plugins/refine/manage_workflows.py, src/nxrefine/plugins/refine/new_experiment.py, src/nxrefine/plugins/refine/new_sample.py, src/nxrefine/plugins/refine/new_scan.py, src/nxrefine/scripts/nxload.py, src/nxrefine/scripts/nxreduce.py
* Adds a new module to handle beamline-specific functions for importing data and logs.
* Provides an 'Import Scans' plugin for importing CHESS scans from existing image directories.
* Modifies the 'New Experiment' plugin to allow initialization of sample directories in a 'nxrefine' sub-directory.
=> Improve-CHESS-imports

src/nxrefine/nxbeamline.py, src/nxrefine/nxdatabase.py, src/nxrefine/nxreduce.py, src/nxrefine/plugins/refine/import_scans.py, src/nxrefine/plugins/refine/make_scans.py, src/nxrefine/plugins/refine/new_experiment.py
* Consolidates all beamline-specific code into the `NXBeamline` class
=> Fix-chess-workflow

src/nxrefine/nxbeamline.py, src/nxrefine/nxreduce.py, src/nxrefine/plugins/refine/choose_parameters.py, src/nxrefine/plugins/refine/manage_workflows.py, src/nxrefine/scripts/nxchoose.py, src/nxrefine/scripts/nxrefine.py
* Fixes bugs in the Manage Workflows and Choose Parameters plugins.
* Fixes argument type of `polar_max` in scripts.
* Fixes metadata loading in `QM2beamline`
=> Minor-fixes

src/nxrefine/nxrefine.py
In `copy_parameters`, the transmission group is diirectly copied from
the parent entry. It is not used otherwise.
=> Remove transmission as a NXRefine attribute

src/nxrefine/nxreduce.py, src/nxrefine/nxserver.py, src/nxrefine/nxsettings.py
* Renames the 'setup' section to 'server' in 'settings.ini'
* Adds server setting to customize executable commands
* Adds server setting to enable/disable concurrent reduce operations
=> Customize-servers

src/nxrefine/nxserver.py, src/nxrefine/nxsettings.py
* Customizes job submission commands for qsub and pdsh.
* Creates a shell script if a template file is specified.
=> Customize different job queue settings

src/nxrefine/nxserver.py
* Fixes a bug with qsub implementation
=> Fix reference to server run command

src/nxrefine/nxdatabase.py
* Adds new nxload command to database status updates.
=> Update status of files loaded with nxload command

src/nxrefine/nxdatabase.py, src/nxrefine/nxreduce.py, src/nxrefine/nxrefine.py, src/nxrefine/nxserver.py
* Updates the nxload status based on either the nxload database entry or raw file existence.
* Fixes a bug in NXServer initialization caused by attempting to update permissions without the necessary privilege.
* Fixes a bug when merging transforms created without the `angles` attribute.
* Removes polarization corrections from CCTW for now.
=> Fix-upload-status

src/nxrefine/nxdatabase.py
* Fixes an issue when relative file paths are used from the wrong directory.
=> Ensure relative paths are correctly specified.

src/nxrefine/nxreduce.py, src/nxrefine/nxserver.py, src/nxrefine/plugins/refine/manage_workflows.py
* Adds CCTW merge output to logs.
* Gives priority to the parent in defining Q-grids.
* Limits the number of active jobs when using qsub.
* Reduces the number of concurrent processes to prevent file locks.
* Improve loading of the Manage Workflows dialog.
=> Improve-cctw-merge

src/nxrefine/nxbeamline.py
* Fixes incorrect assignment of the QM2Beamline `experiment_directory_exists` attribute.
=> Fixes `experiment_directory_exists` attribute

src/nxrefine/nxbeamline.py
* Fixes a bug in setting the scan file name.
=> Fixes setting of the scan file name

src/nxrefine/nxbeamline.py, src/nxrefine/nxlogger.py
* Makes directory specifications in NXBeamline more consistent.'
* Fixes the value of chi at CHESS.
=> Modify-beamline-directories

src/nxrefine/nxlogger.py, src/nxrefine/plugins/refine/refine_lattice.py
* Stop updating fixed parameters when refining angles.
=> Fix-refine-angles

src/nxrefine/nxreduce.py, src/nxrefine/nxsettings.py, src/nxrefine/plugins/refine/choose_parameters.py, src/nxrefine/plugins/refine/new_configuration.py, src/nxrefine/plugins/refine/refine_lattice.py, src/nxrefine/scripts/nxchoose.py, src/nxrefine/scripts/nxrefine.py
* Add hkl_tolerance as a NXReduce setting
* Its value is stored after performing a NXRefine.
=> Add-hkl-tolerance

src/nxrefine/nxsymmetry.py
* Fixes the flip axis for monoclinic symmetry.
=> Change the flip axis for monoclinic symmetry

src/nxrefine/nxbeamline.py
* Fix bug in the metadata path definitions
=> Fix specification of 6-ID-D metadata files

src/nxrefine/nxdatabase.py
* Checks that the raw data file directory exists before checking file existence
=> Fix database bug when updating load status

setup.cfg
NeXpy now searches for entry points contained in installed packages
=> Add an entry point for the plugin directory

src/nxrefine/nxreduce.py, src/nxrefine/nxsettings.py
* Adds beam polarization as a setting.
=> Add polarization as a setting

src/nxrefine/nxserver.py, src/nxrefine/plugins/refine/new_settings.py
* Ensure that all file queue operations are protected by file locking.
* Adds a scroll menu to the New Settings dialog
=> Use context manager to improve file locking

src/nxrefine/nxreduce.py, src/nxrefine/nxsettings.py, src/nxrefine/plugins/refine/edit_settings.py, src/nxrefine/plugins/refine/new_experiment.py
* Improves the logic in defining the experiment path given the default settings.
* Fixes the number of concurrent processes used in multicore systems.
=> Fix-new-experiment

src/nxrefine/nxbeamline.py, src/nxrefine/plugins/refine/import_scans.py, src/nxrefine/plugins/refine/new_experiment.py, src/nxrefine/plugins/server/edit_settings.py
* Ensures that the path to new experiment directories is correctly implemented when there are no default directories.
* Fixes missing attributes in the NXBeamLine class.
* Fixes `Import Scans` dialog when no directory is returned by the file browser.
=> Fix directory settings

src/nxrefine/plugins/refine/new_experiment.py
* Fixes a bug when opening the New Experiment dialog.
=> Fix directory path error messages

src/nxrefine/nxreduce.py
* Fixes `nxfind` and `nxprepare` failures caused by root being read-only
=> Add missing contextual menus to write data

src/nxrefine/nxreduce.py
* Ensures write mode is implemented for `NXMultiReduce` output.
* Minor improvement to code reporting the completion status of `NXMultiReduce` workflow components.
=> Fix-nxreduce-file-modes

src/nxrefine/nxbeamline.py
* Creates entry points so that NXBeamLine subclasses can be defined in separate packages.
* Fixes an issue when the database does not include the completion of a workflow component.
* Fixes an issue with deprecated calls to SqlAlchemy
=> Load entry points to input NXBeamLine subclasses

.github/workflows/sphinx.yml
* Add Pull Requests to the list of documentation action triggers.
=> Allow PRs to trigger documentation updates

src/nxrefine/nxreduce.py, src/nxrefine/nxserver.py, src/nxrefine/nxsettings.py, src/nxrefine/nxutils.py
* Prevents writing to server settings unless specifically requested
* Increases lock timeouts for NXReduce processes
=> Adjust-settings

src/nxrefine/plugins/experiment/new_configuration.py
* Fixes path to the configurations directory when the NXRefine files are in an experiment's subdirectory.
=> Ensure correct directory set for new configuration

src/nxrefine/nxpdf.py, src/nxrefine/plugins/experiment/import_scans.py, src/nxrefine/plugins/experiment/new_configuration.py, src/nxrefine/plugins/experiment/new_scan.py
* Ensures that the correct experiment directory is chosen, when the analysis_path subdirectory is selected.
* Raises dialogs after choosing directories so they are not hidden behind tne main NeXpy window.
=> Fix-import-scans

src/nxrefine/nxserver.py, src/nxrefine/nxsettings.py, src/nxrefine/plugins/experiment/edit_settings.py, src/nxrefine/plugins/experiment/new_experiment.py, src/nxrefine/scripts/nxsettings.py
* Revises NXSettings to reduce unwanted settings files and unintentional overwrites
=> Improve-experiment-setup

src/nxrefine/nxrefine.py, src/nxrefine/nxsettings.py, src/nxrefine/plugins/experiment/new_configuration.py, src/nxrefine/plugins/refine/refine_lattice.py
* Defines the detector orientation using a string containing the detector axes in the lab frame.
* Allows the sample position wrt the goniomater to be defined.
* Improves the updating of settings files when parameters have changed.
=> Add-detector-orientation

src/nxrefine/plugins/refine/refine_lattice.py
* Adds the detector orientation as a parameter in the Refine Lattice dialog.
=> Add detector orientation to refine parameters

src/nxrefine/nxrefine.py, src/nxrefine/nxutils.py
* Creates an importable function to parse the detector orientation when described by a string.
* Improves the definition of NXRefine angle properties, preventing potential recursion issues.
=> Parse-orientation

src/nxrefine/plugins/experiment/create_mask.py, src/nxrefine/plugins/experiment/new_sample.py
* Reconfigures the "Create Mask" dialog to make the UI more intuitive.
* The parameters of all the added shapes can be adjusted in tables to update the added shape.
=> Improve-mask

src/nxrefine/plugins/experiment/new_configuration.py, src/nxrefine/plugins/experiment/new_sample.py
* Creates the sample directories in the analysis path subdirectory if it is defined.
=> Fixes the 'New Sample' dialog when the analysis path is defined

src/nxrefine/nxreduce.py, src/nxrefine/nxrefine.py
* Ensures NXRefine does not fail when a sample group has not been initialized.
* Fixes a bug in summing files caused by hard-wiring specific monitor signal names.
=> Reference-fixes

src/nxrefine/nxdatabase.py, src/nxrefine/nxreduce.py, src/nxrefine/plugins/refine/choose_parameters.py, src/nxrefine/plugins/server/manage_workflows.py
* Allows the Choose Parameters dialog to set the scan file as parent
=> Miscellaneous-fixes

src/nxrefine/nxrefine.py, src/nxrefine/plugins/refine/refine_lattice.py
* Adds checkboxes to the peak list table, which allow peaks to be selected for inclusion in refinements.
* Makes the peak index a masked array to define which peaks to include.
=> Allow peaks to be selected for inclusion in refinements

src/nxrefine/plugins/server/manage_server.py
* Fixes a bug that caused the toggle server button text to be initialized too soon.
=> Ensure the toggle server buttons are initiated before checking run status

src/nxrefine/nxserver.py, src/nxrefine/plugins/server/manage_server.py, src/nxrefine/plugins/server/manage_workflows.py
* Adds a NXController class to handle the task queue when it is internal. It stops the `add_task` function from blocking when waiting before creating the next worker.
=> Add-controller

src/nxrefine/nxreduce.py, src/nxrefine/plugins/server/manage_workflows.py
* Fixes cause of exceptions when determining normalization when preparing transforms.
* Stops Manage Workflows from defining new NXServer instances when adding tasks.
=> Fix normalization

src/nxrefine/nxbeamline.py, src/nxrefine/plugins/experiment/edit_settings.py, src/nxrefine/plugins/refine/calculate_angles.py, src/nxrefine/plugins/refine/find_maximum.py, src/nxrefine/plugins/refine/refine_lattice.py, src/nxrefine/plugins/server/edit_settings.py, src/nxrefine/plugins/server/manage_server.py
* Adds log message when monitor not found
* Improves titles of plugin plots
* Improves formatting of settings dialogs
* Ensures Manage Server dialogs close without exceptions
=> Miscellaneous-improvements

src/nxrefine/nxserver.py
* Uses a file in the nxserver directory to store the previously used CPU number.
* This is used by the NXController class, i.e., when the server is not running as a daemon process.
=> Makes selection of next cpu more robust

src/nxrefine/plugins/refine/choose_parameters.py, src/nxrefine/plugins/refine/find_maximum.py
* Adds a button to plot Q-limits in the 'Choose Parameters' dialog.
* Improves handling of closed plotting windows in the 'Find Maximum' dialog.
=> Add-q-plot

src/nxrefine/nxreduce.py, src/nxrefine/nxutils.py
* Uses the detector pixel mask to mask data before finding peaks.
=> Transfer the pixel mask to the peak search function

src/nxrefine/nxserver.py
* Ensures that the directory to contain server settings in a user's home directory exists.
=> Create private home directory if necessary

src/nxrefine/plugins/experiment/calibrate_powder.py
* Updates the Calibrate Powder plugin to parallelize the auto-generation of powder rings
=> Calibrate-powder-concurrency

src/nxrefine/nxrefine.py
=> Fix scalar output in grid_origin.

src/nxrefine/nxrefine.py
* Hopefully final fix for grid origin bug.
=> Convert grid origin to an array and use tolist function for output.
